/home/luc/hgwork/faggio/docs/api/lino_faggio.fixtures.rst:7: WARNING: autodoc: failed to import module u'lino_faggio.fixtures.eiche'; the following exception was raised:
Traceback (most recent call last):
  File "/home/luc/pythonenvs/py27/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
ImportError: No module named eiche
